### ISSUE TITLE
Thanks! I got a quesstion whether you can give me an answer?

### ISSUE THREAD

**Issue by QZ1314** [Mostro-Complexity/skeletal-action-recognition-cnn#2]
How was that file body model.josn generated?

**Comment by Mostro-Complexity** [comment]
原本是matlab的.mat文件，我用matlab重新生成了json文件。这些文件的生成方法，参考：https://github.com/DingChongyang/STWP-master/tree/33332469055ceabb57f4e13bb2b95067491ba425
和https://github.com/kailiuXD/STWP
---------------------------------------------------------------------------------------------
It was originally a .mat file of matlab, and I regenerated the json file with matlab. How to generate these files, refer to: https://github.com/DingChongyang/STWP-master/tree/33332469055ceabb57f4e13bb2b95067491ba425
And https://github.com/kailiuXD/STWP

**Comment by QZ1314** [comment]
谢谢！
